README.md, default.nix, neuron.cabal, src-bin/Main.hs, src/Neuron/Zettelkasten.hs
Ex:
```
nix-shell --run 'ghcid -c "cabal new-repl exe:neuron" -T ":main /path/to/notesdir rib serve"'
```
=> Allow neuron executable to run on arbitrary notes dir

guide/2011405.md, guide/2011701.md, guide/neuron.dhall, neuron.cabal, src-bin/Main.hs, src-dhall/Neuron.dhall, src/Neuron/Zettelkasten/Config.hs, src/Neuron/Zettelkasten/Route.hs, src/Neuron/Zettelkasten/View.hs
An optional `neuron.dhall` if it exists in the notes directory will be used by Neuron. Otherwise default values will be used. See `./guide/neuron.dhall` for an example. 
Documented at https://neuron.srid.ca/2011701.html
Fixes #15
=> Add configuration support

src/Neuron/Zettelkasten/Link/View.hs, src/Neuron/Zettelkasten/View.hs
This PR adds a link to the `z-index` in the "Navigate up" section as a quick way to go back to the graph view.
NOTE: I'm not familiar with Rib and the Nueron codebase. Please let me know what should be changed.
=> feat(nav): Add z-index on the 'Navigate up' section

guide/2011406.md, guide/2011502.md, guide/2011503.md, guide/2012301.md, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/ID.hs, src/Neuron/Zettelkasten/View.hs
"index.md" is now no longer hardcoded as _the_ overview zettel. Therefore we now have multiple roots, thus the tree becomes a forest.
Consequently,
- "Dangling zettels" list is no more. Because the forest is now generated with all mother vertices as the initial vertices. This is one step towards the clustering feature in #18 
- "Clusters" sections is removed as well. It was a misnomer, which actually showed the strongly-connected components (makes no sense in a zettelkasten).
- Max depth of the left-side tree in the connections pane is now set to 2
=> Remove hardcoded index zettel

default.nix, src/Neuron/Zettelkasten.hs
Fixes #35 and contains https://github.com/srid/rib/pull/137
A side-effect of this change is that neuron will create the Shake database directory `.shake` under the user's notes directory, which is unlikely to be problematic.
=> Add back support for absolute paths

src/Neuron/Zettelkasten.hs
Related to https://github.com/srid/neuron/issues/43
=> Add `-e` / `--editor` flag for `neuron … new` command

guide/2011404.md, guide/2013701.md
Add documentation about mathjax support from zettel markdown.
This is needed because MMark uses unconventional notation for LaTeX input.
Some features also have unexpected bugs as `$$ ... $$` blocks fail to escape some markdown features, in particular superscript and subscript (todo: figure out if these come from mmark-ext or from mathjax directly).
=> Add math support documentation in guide

.gitignore, CHANGELOG.md, README.md, default.nix, guide/2011405.md, guide/2011406.md, guide/2011501.md, guide/2011502.md, guide/2012401.md, guide/2013501.md, neuron.cabal, src-bin/Main.hs, src/Neuron/Zettelkasten.hs, src/Neuron/Zettelkasten/CLI.hs, src/Neuron/Zettelkasten/Config.hs, src/Neuron/Zettelkasten/ID.hs, src/Neuron/Zettelkasten/Route.hs, src/Neuron/Zettelkasten/Store.hs, src/Neuron/Zettelkasten/Zettel.hs, test/Neuron/VersionSpec.hs, test/Neuron/Zettelkasten/IDSpec.hs
=> CLI revamp

guide/2011403.md, guide/2011501.md, neuron.cabal, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/ID.hs, src/Neuron/Zettelkasten/Link/Action.hs, src/Neuron/Zettelkasten/Link/View.hs, src/Neuron/Zettelkasten/Route.hs, src/Neuron/Zettelkasten/Store.hs, src/Neuron/Zettelkasten/View.hs, test/Neuron/Zettelkasten/IDSpec.hs, test/Neuron/Zettelkasten/Link/ActionSpec.hs
Allow either neuron's ID scheme, or a custom alphanumeric (with hyphen and underscore) scheme. Nothing else will be permitted in the zettel ID.
Resolves #70
=> Explicit ID scheme

default.nix
This allows declarative installations to pin the nixpkgs version to
enable deterministic builds and overrides.
=> Nix derivation: accept pkgs as an arg

src/Neuron/Zettelkasten/Markdown.hs, src/Neuron/Zettelkasten/Markdown/Extension.hs
Fixes #91 
This PR adds a MMark extension to render tables with classes.
=> feat(website): Add MMark extension to render table with styles

src/Neuron/Zettelkasten/Store.hs, test/Neuron/Zettelkasten/StoreSpec.hs
I made a typo and transposed a couple of numbers in a zettel link. I was
getting an error message like `No such zettel: ZettelDateID 2020-03-19`,
but since there were a bunch of links in the doc, it took me a while to
figure out that this corresponded to the `[2011401]` link in my doc.
I've changed the error message for date IDs to include the text as it
would actually appear in the link in addition to the parsed day/index.
It would probably also be nice to get source line numbers on error
messages, but that sounds like a more ambitious effort.
I've never really written Haskell, so if I'm doing anything weird, it's
for no good reason, and please let me know.
=> ZettelStore: more helpful lookup failure message

guide/2011506.md, src/Neuron/Zettelkasten/Link.hs, src/Neuron/Zettelkasten/Link/Theme.hs, src/Neuron/Zettelkasten/Link/View.hs, src/Neuron/Zettelkasten/Query.hs, src/Neuron/Zettelkasten/Tag.hs, test/Neuron/Zettelkasten/Link/ThemeSpec.hs, test/Neuron/Zettelkasten/LinkSpec.hs
Resolves #118
Needs to be manually enabled using `?grouped` in the query.
=> Group zettels by matching tag

neuron.cabal, src-bin/Main.hs, src/Neuron/CLI/Types.hs, src/Neuron/Web/Generate.hs, src/Neuron/Web/Route.hs, src/Neuron/Web/View.hs, src/Neuron/Zettelkasten/Error.hs, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/ID.hs, src/Neuron/Zettelkasten/Link.hs, src/Neuron/Zettelkasten/Link/Theme.hs, src/Neuron/Zettelkasten/Link/View.hs, src/Neuron/Zettelkasten/Query.hs, src/Neuron/Zettelkasten/Store.hs, test/Neuron/ConfigSpec.hs, test/Neuron/Zettelkasten/Link/ThemeSpec.hs, test/Neuron/Zettelkasten/QuerySpec.hs, test/Util.hs
Resolves #120 and ameliorates #104
Also improves error messages, which now look like:
```
user error (
The zettel file '2008316.md' is malformed
it contains a query URI (zquery://search/?linkTheme=foo) with invalid link theme (foo)
)
```
```
user error (
The zettel file '2008316.md' is malformed
it contains a query URI (zquery://foo/) with unsupported host
)
```
```
user error (
The zettel file '2008316.md' is malformed
it references a zettel <1234567> that does not exist
)
```
=> Refactor error handling

src-bash/neuron-search/default.nix
`neuron rib -wS` spawns a http sever, but this command tried to open a https server. Additionally, the echo command was missing the `$` required to work. Now pressing ctrl-j in `neuron search` works as expected.
While browsing the issues, I also stumbled upon #56 and fixed that as well.
There remains the issue that if there are no markdown files in `NOTESDIR`, the script will exit with an error along the lines of:
```sh
*.md: IO error for operation on *.md: No such file or directory (os error 2)
```
which might not be desirable, but it's certainly a highly unusual circumstance given the nature of `neuron search`. 
Closes #56
=> Fix small issues in neuron-search

guide/2011701.md, neuron.cabal, src-bin/Main.hs, src/Data/Structured/Breadcrumb.hs, src/Neuron/Config.hs, src/Neuron/Web/Route.hs, src/Neuron/Web/View.hs
Generated based on the zettelkasten graph. And matches the "Navigate Up" tree.
Enabed only if `siteBaseUrl` is set in neuron.dhall
For #27
=> Add JSON-LD breadcrumbs to published site

guide/2011503.md, guide/2011504.md, guide/2011506.md, guide/2017401.md, src/Data/Graph/Labelled.hs, src/Data/Graph/Labelled/Algorithm.hs, src/Data/Graph/Labelled/Type.hs, src/Neuron/Web/View.hs, src/Neuron/Zettelkasten/Connection.hs, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/Graph/Type.hs
Revamp the graph type to represent all types of links (zcf included), and show the full range of backlinks in connections panel (i.e., including zcf backlinks).
Resolves #34
=> True backlinks support

neuron.cabal, src-bin/Main.hs, src/Neuron/CLI/New.hs, src/Neuron/CLI/Query.hs, src/Neuron/CLI/Types.hs, src/Neuron/Web/Generate.hs, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/ID.hs, src/Neuron/Zettelkasten/ID/Scheme.hs, test/Neuron/Zettelkasten/ID/SchemeSpec.hs
Also adds `--id=<custom>` and `--id-date`. 
Date ID is still the default .
And `neuron new` adds the creation date to the zettel metadata regardless of the ID scheme used.
For #151
=> Add `neuron new --id-hash` for random hash IDs

src/Neuron/CLI/Types.hs
Just a quick typo fix.
I was looking around for some Haskell Nix example projects and found this. Cheers for your work work, it was super easy to build and test.
=> Fixes typo in function name

CHANGELOG.md, guide/2011503.md, guide/2013101.md, guide/2017401.md, neuron.cabal, src/app/Main.hs, src/app/Neuron/Web/View.hs, src/app/Neuron/Zettelkasten/Graph.hs, src/lib/Data/Graph/Labelled.hs, src/lib/Data/Graph/Labelled/Algorithm.hs, src/lib/Neuron/Zettelkasten/Connection.hs, src/lib/Neuron/Zettelkasten/Query/View.hs, src/lib/Neuron/Zettelkasten/Zettel/View.hs, test/Neuron/VersionSpec.hs
This is a major UI change. 
- ~~[ ] Consider folding it with a linear breadcrumb as [accordion](https://semantic-ui.com/modules/accordion.html)?~~
- ~~[ ] Or use dual UI (tree vs linear breadcrumbs), picking one from neuron.dhall~~
- This addresses the removal of 'Down' links
=> Revamp "connections panel" with something entirely different

CHANGELOG.md, neuron/src/app/Neuron/CLI.hs, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Type.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs
Exports the entire graph as JSON. Includes everything but the zettel content text.
This query cannot be used in zettel linking. In neuron there are now two kinds of queries -- one runs against a list of zettel files, and affects the graph; the other (added in this PR) operates on the built graph itself, and thus cannot be used in zettels.
=> Add: `neuron query --graph`

dep/dependent-sum-aeson-orphans/default.nix, dep/dependent-sum-aeson-orphans/github.json, dep/dependent-sum-aeson-orphans/thunk.nix, guide/2014401.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Web/Generate.hs, neuron/src/lib/Data/TagTree.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Connection.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Build.hs, neuron/src/lib/Neuron/Zettelkasten/ID.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Error.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Error/Internal.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Theme.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Type.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel/Parser.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs, neuron/test/Neuron/Zettelkasten/ZettelSpec.hs, project.nix
Include zettel queries in the zettel metadata (they will also appear in `neuron query --graph` JSON) such that a graph can be patched (with modified/new/deleted zettels) without depending on the original zettel text or Pandoc documents.
=> Patchable graph

neuron/neuron.cabal, neuron/src/app/Main.hs, neuron/src/app/Neuron/Web/Generate/Route.hs, neuron/src/app/Neuron/Web/View.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/Route.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/test/Neuron/VersionSpec.hs
Benefits:
* Keeps zettel body centered (current left-sidebar-menu pushes it to right a bit)
* Consistent view on mobile and desktop (actions are always found at the top on any device)
* Emphasized further with theme color
* Appears in all pages (including z-index and search)
* To be used, and expanded, by the upcoming web app version
=> New nav bar

neuron/neuron.cabal, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/ZIndex.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Build.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/test/Neuron/VersionSpec.hs
This affects the `neuron query` JSON slightly:
- `errors` field is renamed to `skipped` (because it contains zettels that failed to parse, hence "skipped")
- A new `error` field will be present for `--id` queries (or `--uri <id>`), if and only if the zettel ID being queried does not exist.
There should be no change to the `result` or `query` fields.
=> Propagate query result errors to the graph

neuron/src/app/Main.hs, neuron/src/app/Neuron/CLI/New.hs, neuron/src/app/Neuron/Web/Generate.hs, neuron/src/app/Neuron/Web/StructuredData.hs, neuron/src/app/Neuron/Web/View.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/Route.hs, neuron/src/lib/Neuron/Web/ZIndex.hs, neuron/src/lib/Neuron/Web/Zettel/CSS.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Build.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel/Parser.hs, neuron/test/Neuron/Zettelkasten/ZettelSpec.hs
=> Render raw zettel on parse errors

neuron/src/app/Neuron/CLI/New.hs, neuron/src/app/Neuron/CLI/Types.hs
Late Zurihac PR `:P`
Now, if the user does not pass an argument for the title, a default '# Zettel created on <date>' is used.
Made the change in the action that writes the file instead of in the command line parser because that is written with an applicative parser so I couldn't figure out if I could use the value of a parameter (date) to build the default for another parameter (title).
fixes #232
=> Make neuron new title argument optional (fix #232)

.gitignore, ci.nix, default.nix
=> Cleaning unnecessary Nix deps using remove-references-to 

guide/2011503.md, guide/2011504.md, guide/index.md, neuron/neuron.cabal, neuron/src/lib/Data/Graph/Labelled.hs, neuron/src/lib/Data/Graph/Labelled/Algorithm.hs, neuron/src/lib/Neuron/Web/ZIndex.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/test/Neuron/VersionSpec.hs
- Get rid of cycle checks (fixes #247)
- Switch from 'DFS forest' to 'BFS forest' algorithm for uplink tree, etc.
- Display zettelkasten stats in the z-index
=> Folgezettel tree improvements

neuron/src/app/Neuron/CLI/Types.hs, neuron/src/lib/Data/Graph/Labelled/Algorithm.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Graph.hs
Work in progress: do not merge.
Will be useful for editors to show a "nearby zettels" view.  See
felko/neuron-mode#30 for more details.
=> Implement a backlinks query for a given Zettel ID

neuron/src/app/Neuron/CLI.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs
Fixes #254, needed for <https://github.com/felko/neuron-mode/issues/30>
The new JSON output looks like this:
- `--backlinks-of`
```json
{
"skipped": {},
"result": [
{
"path": "guide/2011402.md",
"connection": "Folgezettel",
"day": "2020-03-19",
"id": "2011402",
"title": "Guide",
"tags": []
},
{
"path": "guide/2011406.md",
"connection": "OrdinaryConnection",
"day": "2020-03-19",
"id": "2011406",
"title": "Creating and Editing zettels",
"tags": [
"walkthrough"
]
},
...
],
"query": [
"GraphQuery_BacklinksOf",
[
null,
"2011403"
]
]
}
```
- `--uplinks-of`
```json
{
"skipped": {},
"result": [
{
"path": "guide/2011402.md",
"connection": "Folgezettel",
"day": "2020-03-19",
"id": "2011402",
"title": "Guide",
"tags": []
}
],
"query": [
"GraphQuery_BacklinksOf",
[
"Folgezettel",
"2011403"
]
]
}
``` …
=> Make graph queries output JSON that is consistent with zettel queries

.github/workflows/ci.yaml, ci.nix, default.nix, guide/2012401.md, guide/6479cd5e.md, project.nix, shell.nix
This PR modifies the `default.nix` and `shell.nix` files to take arguments with defaults which are then provided to `project.nix` (which no longer takes arguments). 
This is necessary for systems which use [Nix flakes](https://www.tweag.io/blog/2020-05-25-flakes/), where `builtins.currentSystem` cannot be used. Previously, there was no mechanism for users to stop `project.nix` from using `builtins.currentSystem` when importing `default.nix` and so it just couldn't be imported.
Unfortunately, this is technically a breaking change - while `nix-build` will still work unchanged, importing the repository as before won't work and will need to be changed (as shown in the changes to the guide).
=> Avoid requiring `builtins.currentSystem`

project.nix
Recent changes since #264 have broken evaluation in pure evaluation mode (required when using this project from a Nix flake), this PR fixes that regression. If maintaining the `sha256` argument to `fetchTarball` is bothersome, then you might consider adopting [`niv`](https://github.com/nmattia/niv) to make updating the pinned external repositories easier.
=> Fix evaluation in pure evaluation mode

docker.nix
This makes it more convenient to build custom images (possibly with shell included) using `--arg` flags in `nix-build`.
=> Make `docker.nix` configurable, add option to include shell

guide/778816d3.md
Links to [modified version of `neuron-template`](https://gitlab.com/thematten/neuron-template) that works with GitLab Pages.
=> Update "Automatic Publishing" to include GL Pages

guide/2012401.md
Fixing a typo in the first command that results in a `x is not of type package` error when trying to add it to a package list.
=> Fix declarative install command from master branch

guide/2012401.md
Unquoted URLs are deprecated. (I believe. I don't remember what version did that.)
=> Quote URLs in Nix examples

CHANGELOG.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI.hs, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Web/Cache.hs, neuron/src/app/Neuron/Web/Generate.hs
Cache the zettelkasten graph on disk, and add a `--cached` option to `neuron query` for speed. The cache is updated only by `neuron rib`. The cache file is stored at `.neuron/cache.json`.
Addresses a part of #321
=> Cache zettelkasten graph JSON on disk

neuron/neuron.cabal, neuron/src/app/Neuron/Web/Cache.hs
… otherwise `neuron new` fails with this error message on first-time setup:
```
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:
at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.19.1-9t93in5US46FSh4fNQCGA:Development.Shake.Forward
* Raised the exception:
./.neuron/cache.json: openBinaryFile: does not exist (No such file or directory)
```
=> Create `.neuron` directory if missing

guide/2013701.md
The multi-line example renders in a single line. 
The proposed fix renders it correctly.
=> Fix MathJax multi-line example

CONTRIBUTING.md, project.nix
It bugged me to have to remember to pack/unpack, and edit the project.nix file. So now you don't have to edit the project.nix file after unpacking any of the obelisk dependencies.
Opted for the simplest possible thing rather than trying to get fancy with throwing an error message if someone manages to mess things up somehow. Ideally, if this is merged there shouldn't be any reason to even look at the project.nix file (for most simple contributions)
=> Autodetect thunks vs unpacked obelisk dependencies to simplify development

neuron/src/lib/Neuron/Reader/Markdown.hs
This enables full support for [fancy lists](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/fancy_lists.md) in neuron (on the backend). Requires the [identically named PR](https://github.com/srid/reflex-dom-pandoc/pull/7
) in srid/reflex-dom-pandoc in order to actually take advantage of this; otherwise the markdown AST won't be transformed into the correct HTML.
=> Support fancy lists (ordered list attributes)

dep/commonmark-hs/default.nix, dep/commonmark-hs/github.json, dep/commonmark-hs/thunk.nix, project.nix
Removes manual commonmark references because we don‘t need it with newer
nixpkgs
=> Bump nixpkgs and clean-up default.nix

neuron/src/lib/Neuron/Web/Query/View.hs
Does the thing but more better and less wronger. Fixes #255
=> Use superscript on folgezettel links to denote connection

dep/reflex-dom-pandoc/github.json, guide/2011504.md, guide/2017401.md, guide/5e41fd32.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Config/Alias.hs, neuron/src/app/Neuron/Web/Generate.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/ZIndex.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Connection.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Build.hs, neuron/src/lib/Neuron/Zettelkasten/ID.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/test/Neuron/Zettelkasten/ID/SchemeSpec.hs, neuron/test/Neuron/Zettelkasten/IDSpec.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs
Addresses a part of #312 as well as **drops support for legacy links** <sup>(the 'zcfquery' ones)</sup>.
Example:
```markdown
This is [a regular note](foo-bar.md) link. Neuron will treat it as a `cf` link
```
Uses https://github.com/srid/reflex-dom-pandoc/pull/8
=> Support regular Markdown links

CHANGELOG.md, guide/2011404.md, guide/2011505.md, guide/2014401.md, guide/535407ad.md, neuron/neuron.cabal, neuron/src/lib/Neuron/Reader/Markdown.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel/Parser.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs
=> Add inline tags support

guide/2011701.md
I was interested in removing the edit navbar button since I use a local text editor for my editing.  Turns out we can just remove the editUrl entry from the configuration to do this.  This change adds a note about this to the documentation.
=> Add note about removing editUrl to avoid navbar button

neuron/src/app/Main.hs, neuron/src/app/Neuron/Config.hs, neuron/src/app/Neuron/Web/View.hs, neuron/src/lib/Neuron/Config/Type.hs, neuron/src/lib/Neuron/Web/HeadHtml.hs
Adds `headHtml : Optional Text` option to the configuration. It can be set in one of two ways, but not both simultaneously.
- The option can be set as usual in `./neuron.dhall`.
- If the file `./head.html` exists, then `headHtml` is set to `Some [head.html's contents]`.
Addresses #362 directly. Also solves or enables workarounds for several other issues (e.g. #212, #361, #383).
=> Allow custom HTML in `<head>`.

neuron/neuron.cabal
This is the version that introduces an orphan instance for Some,
needed to derive ToJSON/FromJSON instances for `Zettel` in
`lib/Neuron/Zettelkasten/Zettel.hs`.
=> Add lower bound dependent-sum-aeson-orphans >= 0.2.1.0

guide/2011403.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Config/Alias.hs, neuron/src/app/Neuron/Reader/Org.hs, neuron/src/app/Neuron/Web/Generate/Route.hs, neuron/src/app/Neuron/Web/View.hs, neuron/src/app/Neuron/Zettelkasten/ID/Scheme.hs, neuron/src/lib/Neuron/Reader/Markdown.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/ZIndex.hs, neuron/src/lib/Neuron/Zettelkasten/ID.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Error.hs, neuron/test/Neuron/Config/AliasSpec.hs, neuron/test/Neuron/VersionSpec.hs, neuron/test/Neuron/Zettelkasten/ID/SchemeSpec.hs, neuron/test/Neuron/Zettelkasten/IDSpec.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs, neuron/test/Neuron/Zettelkasten/Zettel/ParserSpec.hs, neuron/test/Neuron/Zettelkasten/ZettelSpec.hs
For #399 
Allows links like:
```
[[[Hello World]]]
```
which is converted to the URI:
```
<z:link/Hello%20World>
```
generating `Hello_World.html`.
---
=> Allow whitespace in Zettel ID

CHANGELOG.md, guide/index.md, neuron/neuron.cabal, neuron/src/lib/Neuron/Reader/Markdown.hs
Add [bracked_spans](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/bracketed_spans.md) extension to Markdown parser.
This extension allows setting custom html attributes (such as the Semantic UI classes from #176) on any inline text. For example:
```markdown
This is a paragraph [with this text]{.ui .red .text} in red.
```
which renders as:
=> Bracketed spans in Markdown

project.nix, static.nix
This allows passing a `pkgs` argument to `project.nix` to prevent the pinned nixpkgs from being evaluated.
I use that in my flaked home-manager setup (where evaluating nixpkgs is not possible if a system is not explicitly passed).
=> Make sure we don't use the pinned nixpkgs if another one is provided

CHANGELOG.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/Search.hs
Reverts srid/neuron#429
To temporarily resolve regression #430
=> Revert "Embed neuron-search script"

neuron/src/lib/Neuron/Reader/Markdown.hs, neuron/test/Neuron/Zettelkasten/Zettel/ParserSpec.hs
Resolves #441
I was thinking about something a little more extensible, e.g.
```haskell
some (noneOfToks $ [Spaces, UnicodeSpace, LineEnd] <> fmap Symbol excludedChars)
where excludedChars = "],."
```
but I figured this list probably won't be growing or changing much, and I figured the simple/ expanded version I'm proposing reads a little more smoothly. Let me know if you have a preference one way or the other! (Also please let me know if any other characters should be excluded from the parse.)
=> Exclude punctuation from inline tag parse

guide/markdown.md, guide/raw-html.md, guide/using-html-in-markdown.md
This PR adds documentation for using HTML in Neuron markdown.
Because Neuron scans notes for links before passing them to the MD parser, and because Neuron still supports `<note-name>` link syntax, it treats simple HTML elements as notes, which result in missing/unknown note warnings.
The documentation added covers two solutions:
1. Using Commonmark raw-attribute syntax as noted in https://github.com/srid/neuron/issues/437#issuecomment-710698849
2. Adding an HTML attribute to the element
Adds documentation for #437
---
I discovered the option of adding HTML attrs when I was wondering why an `iframe` worked in a note without the raw-attribute syntax, but `video` didn't. It has worked for every basic HTML element I've tried to use it for without issue.
The upside, is that the Markdown is …
=> Documentation for using raw HTML in notes

CHANGELOG.md, neuron/neuron.cabal, neuron/src-bash/neuron-search
I "hacked" `neuron/src-bash/neuron-search` to include all zettel, also those that previously were not listed because they don't have an explicit `title: ` in the header, nor a `# <title>` line. 
I have many "legacy" zettel imported from iA writer, Ulysses, nvAlt and such where the convention was to use `## <title>` to generate filename etc. Currently they don't show up in the `neuron search` function. That's really not good. 
I think the `neuron` convention is to use the filename as title if there is none specified, which this PR takes care of.
It's a bit of a kludge, but it seems to work fine. Maybe someone with more `bash` expertise can clean it up later. 
Also changed the `xarg` call to deal with filenames that contain blanks.
=> make search include zettel with no explicit title, use filename instead

nix/sources.json, project.nix
Edit, because I forgot the context: Hey there! I'm install neuron in my own flake-based setup, where I try to use a single nixpkgs if possible. I had to make a few changes to upgrade it to the latest nixpkgs, so I though I'd send them here.
I modified the skylighting pinning to work on newer nixpkgs versions where 0.10.0.2 doesn't exist, and 0.10.0.3 is the default.
I bumped nixpkgs while I was at it, but feel free to drop that commit if you don't want it upgraded.
I didn't touch the static nixpkgs, because I couldn't run it on my osx setup, thus I ensured to keep the changes backward-compatible.
=> Allow for a newer nixpkgs, and bump nixpkgs

neuron/src/lib/Neuron/Reader/Markdown.hs
`pipeTableSpec` should also be after `defaultSyntaxSpec`
Fixes #469 & fixes #465
=> Fix more parsing issues with pipe characters

guide/chartjs.md, guide/graphviz.md, guide/mermaid-js.md
Adding some guide for client-side rendering tricks we can use with neruon.
As all of it is implemented with similar logic, 
I think it would be better to write an integration guide at the "master node" explaining that you can use it with "head.html" or raw html inside each zettel.
All 3 Zettels only include code and examples.
=> Add guide for custom javaScript actions.

guide/Plugins/Directory Tree.md
This is the only thing I stumbed on--otherwise the documentation for the `dirtree` plugin was clear for me.
=>  Clarify that directories/note IDs must be globally unique when using the dirtree plugin

CHANGELOG.md, dep/nixpkgs/github.json, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/App.hs, neuron/src/app/Neuron/CLI/Logging.hs, neuron/src/app/Neuron/CLI/New.hs, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Config.hs, neuron/src/app/Neuron/Reactor.hs, neuron/src/app/Neuron/Reactor/Build.hs, neuron/src/app/System/Directory/Contents/Extra.hs, neuron/src/lib/Data/TagTree.hs, neuron/src/lib/Neuron/Frontend/Manifest.hs, neuron/src/lib/Neuron/Frontend/Route.hs, neuron/src/lib/Neuron/Frontend/Route/Data/Types.hs, neuron/src/lib/Neuron/Plugin/PluginData.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs
Avoid re-rendering of unchanged zettel routes when using `-w`. Use headless reflex network to propagate changes and render only changed routes. This is phase 1 of #321 - and more optimizations are to come.
With this PR, `neuron gen -w` will re-generate a bit faster when files are modified (no change has been made however to the _initial_ generation's performance).
=> Speed up incremental generation

guide/Plugins/Directory Tree.md
This PR adds documentation for the **Directory Tree** plugin explaining the rationale behind requiring that directory names be globally unique.
I started with your comment on the last PR, and tried to break it down and give more concrete detail. Hoping this works, and I'm more than happy to make changes to it.
=> [DOCS] Explain rationale for lifting subdir notes out of hierarchy

neuron/src-bash/neuron-search
Resolves  #463
This PR adds the `--exact` option to `fzf` when using full text search by checking if `FILTERBY` is empty.
=> Use --exact with full text search

.github/workflows/ci.yaml
Advance the nightly tag on master branch build. 
Used a `github-script` that deletes the tag (if present) and recreates it on the current `master` commit.
=> Closes #444: advance the nightly tag

CHANGELOG.md, neuron/neuron.cabal, neuron/src-bash/neuron-search
I found searching quite difficult, and had this in mind for a while.
These are only bash changes on how neuron interacts with `fzf` and `bat`
- Highlight line with `bat --highlight-line`
- Changed FZF to focus on the line with `fzf --preview-window ':+5-5'`
- Made the focuse'd line configurable via `NEURON_SEARCH_CONTEXT_ABOVE` environment variable, but defaults to `10` (lines above search result) *(edit: changed from 5 to 10)*
Before:
[![asciicast](https://asciinema.org/a/391208.svg)](https://asciinema.org/a/391208)
After:
[![asciicast](https://asciinema.org/a/391205.svg)](https://asciinema.org/a/391205)
=> `neuron search`: highlight matching line

doc/Guide/Creating and Editing zettels/editor.md
Adds a link to my neuron-v2 vim8/neovim plugin. This plugin may be merged upstream later, but for now it's separate.
See [this issue](https://github.com/fiatjaf/neuron.vim/issues/62) for tracking the upstream bug report.
=> Add neuron-v2 vim plugin link

CHANGELOG.md, doc/Guide/Web interface/Customizing the generated website/Custom JavaScript and CSS.md, doc/Guide/Zettel Markdown.md, doc/Guide/Zettel Markdown/2013702.md, doc/Guide/Zettel Markdown/Code syntax Highlighting.md, neuron/neuron.cabal, neuron/src/app/Neuron/Frontend/Static/HeadHtml.hs, neuron/src/lib/Neuron/Frontend/Zettel/CSS.hs, neuron/src/lib/Neuron/Frontend/Zettel/View.hs
Resolves #542
- explain how to change syntax highlighter via `head.html`
- use slug
=> Use prism.js for syntax highlighting (and allow users to use a different one)

doc/Guide/extras.md
[`zk`](https://github.com/mickael-menu/zk) is a command-line tool helping you to maintain a plain text Zettelkasten or personal wiki.
While there is some overlap with neuron's features, both tools are actually useful when paired together:
* Neuron shines with its static website generation
* `zk` has powerful [filtering](https://github.com/mickael-menu/zk/blob/main/docs/note-filtering.md) and [note generation](https://github.com/mickael-menu/zk/blob/main/docs/note-creation.md) capabilities
Close integration with Neuron was thought through from the start when designing `zk`. For example, Neuron's [Folgezettel](https://neuron.zettel.page/folgezettel.html) syntax is supported: `[[[link]]]`, `#[[link]]` and `[[link]]#`.
But you can make your [`zk` …
=> Add zk to the user-contributed utilities

.github/workflows/ci.yaml, .gitignore, ci.nix, default.nix, dep/nixpkgs/default.nix, dep/nixpkgs/github.json, dep/nixpkgs/thunk.nix, docker.nix, flake.lock, flake.nix, neuron.cabal, nixpkgs.nix, project.nix, shell.nix, static.nix
This should solve #485.
With this `flake.nix`, we can do...
- use `nix build` to build
- use `nix shell` to enter build shell
- use `nix run` to run `neuron` even without cloning project
- for instance, `nix run "github:TheKK/neuron#neuron" -- open`
I also add `result-data` to `.gitignore` since it was created after running `nix build`. This make you to run `nix-build` to build same derivation after `nix build`.
If there's anything I can improve, please let me know!
=> flake.nix: add basic support

doc/Installing/Declarative Install.md
Since when the default.nix file has switched to be a "proxy" to the
flake, the use of @edolstra compatibility layer moved the package to the
"default" member.
=> Fix the documentation of the declarative install method

doc/Installing/Declarative Install.md
`import xxx {}` only works if `xxx` is a function. Neuron's output is not a function, so installing per these instructions fails with `attempt to call something which is not a function but a set`.
=> Fix Declarative Install instructions

CHANGELOG.md, neuron.cabal, src/Neuron/Frontend/Static/StructuredData.hs
In order to make javascript-based tools which can effectively work with `cache.json` and transform certain things for the page, having zettel metadata somewhere in the HTML would be useful. At a minimum, the zettel slug ID is all that's required to cross-reference against `cache.json`.
Just to get the ball rolling, I've added `<meta>` elements (for the page ID, slug ID, and each tag) in the the head section for every zettel (thanks for the pointers @srid !).
The elements will be of the form
```html
<meta content="my page id" property="neuron:zettel-id">
<meta content="my-slug-id" property="neuron:zettel-slug">
<meta content="tag1" property="neuron:zettel-tag">
<meta content="tag2" property="neuron:zettel-tag">
<meta content="tag3" property="neuron:zettel-tag">
```
=> Add zettel metadata to HTML head <meta>

CHANGELOG.md, neuron.cabal, src/Neuron/CLI/Parser.hs, src/Neuron/CLI/Query.hs, src/Neuron/CLI/Types.hs
To support querying by tools which expects whole information on one
line. E.g. Neovim telescope plugin where I need to query neuron DB returns result split on multiple lines. Which is nice for human, however impose burden on program interaction.
This PR introduces the --jsonl flag to 'query' sub-command. If this flag is active one entry will be printed at each line. 
Which is super convenient format for command line processing.
Example
```
neuron/doc $ /nix/store/i5lagbbinqf4i5b77liz3qp5spih98nd-neuron-1.9.27.2/bin/neuron query  --id index
Plugins enabled: dirtree, links, tags, uptree
Loading directory tree (49 .md files) ...
Building graph (49 notes) ...
[
{
"ID": "index",
"Meta": {
"dirtree": {
"display": false
},
"tags": []
},
"Path": "./index.md",
"Slug": "index",
"Title": "Neuron …
```
=> Introduce JSONL format for query

CHANGELOG.md, doc/Guide/Plugins/Linking.md, neuron.cabal, src/Neuron/Plugin/Plugins/Links.hs
Let me know if there are any issues.
I didn't add tests because there are currently no tests for parsing the wikilinks anyway.
This is technically a breaking change if anyone has pipes in their wikilinks, but I don't think that's a huge problem.
There's also both styles of `[[url|name]]` and `[[name|url]]` in use; I went with the former because it works better with the defaults in the recommended VSCode configuration.
Resolves #373
=> Add named wikilink processing

flake.nix, home-manager-module.nix
Main change is the added home-manager module, which can be used like 
```
neuron = {
enable = true;
notesDirectory = "/home/${name}/zettelkasten";
prettyUrls = true;
};
```
See https://github.com/divnix/devos/issues/106#issuecomment-782914232 for pointers about how to add a home-manager module from a flake to `imports`.
I also removed the unnecessary app definitions, since by default `nix run` will try the packages with the same name. App definitions are mainly useful if there are multiple binaries or you want to name them differently.
=> Provide homeManagerModule as a flake output
