srid/neuron

default.nix, example/srid.ca/Main.hs, neuron.cabal, src/Neuron/Zettelkasten/Route.hs, src/Neuron/Zettelkasten/View.hs
Based on https://github.com/srid/rib/pull/118
Closes #4
=> Add Open Graph support

src-bin/Main.hs
Support for rendering math would be nice, I hope the MathJax dependency is not a problem
=> Math support

guide/2011406.md, guide/2011503.md, guide/2012301.md, src-bin/Main.hs, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/View.hs
=> Graph cluster detection

default.nix, neuron.cabal, src/Neuron/Zettelkasten.hs, src/Neuron/Zettelkasten/Version.hs
Fixes: https://github.com/srid/neuron/issues/40
=> Add --version CLI argument

neuron.cabal, src-bin/Main.hs, src-dhall/Config/Default.dhall, src-dhall/Config/Type.dhall, src/Neuron/Zettelkasten/Markdown.hs, src/Neuron/Zettelkasten/Store.hs, src/Neuron/Zettelkasten/View.hs
=> Allow disabling mathjax support in config

default.nix, guide/2011501.md, guide/2012401.md
=> Access git rev from the environment

src/Neuron/Zettelkasten/View.hs
=> Display the zettel tags

guide/2011405.md, guide/2011701.md, guide/2014601.md, neuron.cabal, src-bin/Main.hs, src-dhall/Config/Default.dhall, src-dhall/Config/Type.dhall, src/Neuron/Zettelkasten/Theme.hs, src/Neuron/Zettelkasten/View.hs
Resolves #22 
Default theme:
Available themes:
=> Theming support

CHANGELOG.md, guide/2011701.md, neuron.cabal, src-bin/Main.hs, src-dhall/Config/Default.dhall, src-dhall/Config/Type.dhall, src/Neuron/Parser.hs, src/Neuron/Zettelkasten.hs, src/Neuron/Zettelkasten/Config.hs, src/Neuron/Zettelkasten/ID.hs, src/Neuron/Zettelkasten/Route.hs, src/Neuron/Zettelkasten/View.hs, test/Neuron/Zettelkasten/ConfigSpec.hs
So that srid.ca can eventually use neuron directly instead having to extend it as a library.
=> Add support for custom alias redirects

guide/2011405.md
=> Mention -s host:port and --help in web interface docs

guide/2013501.md, src/Neuron/CLI.hs, src/Neuron/Web/View.hs, src/Neuron/Zettelkasten/Link/Action.hs, src/Neuron/Zettelkasten/Link/View.hs, src/Neuron/Zettelkasten/Query.hs
=> Make `neuron query` return only zettels in JSON

.github/workflows/ci.yaml, bin/run, bin/test, default.nix, neuron.cabal, src/Neuron/CLI.hs, src/Neuron/CLI/Types.hs, src/Neuron/Web/View.hs, src/Neuron/Zettelkasten/Graph.hs, src/Neuron/Zettelkasten/Link.hs, src/Neuron/Zettelkasten/Link/Theme.hs, src/Neuron/Zettelkasten/Link/View.hs, src/Neuron/Zettelkasten/Query.hs, src/Neuron/Zettelkasten/Tag.hs, test/Neuron/VersionSpec.hs, test/Neuron/Zettelkasten/LinkSpec.hs, test/Neuron/Zettelkasten/QuerySpec.hs, test/Neuron/Zettelkasten/TagSpec.hs
Also adds the query type for implementing #110
=> Refactor query types

ci.nix
=> Push nix-shell derivations to cachix on CI

neuron.cabal, src/app/Data/Structured/Breadcrumb.hs, src/app/Main.hs, src/app/Neuron/Web/View.hs
=> Lucid => Reflex DOM

CHANGELOG.md, dep/reflex-dom-pandoc/github.json, src/app/Main.hs, src/app/Neuron/Web/View.hs, src/lib/Neuron/Markdown.hs, src/lib/Neuron/Zettelkasten/Query/View.hs, src/lib/Neuron/Zettelkasten/Zettel/View.hs
Looks like I messed up some things
=> Reapply #191

guide/2011504.md, neuron/neuron.cabal, neuron/src/lib/Neuron/Markdown.hs, neuron/test/Neuron/VersionSpec.hs
Support `[[...]]` syntax for linking in addition to `<..>`.
=> Allow support for wiki-style links

neuron/neuron.cabal, project.nix
Implemented using https://github.com/NixOS/nixpkgs/pull/49714
=> Enable shell completion

.github/workflows/ci.yaml, .gitignore
=> Generate Linux nix-bundle in CI

guide/cc1f7ecf.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI.hs, neuron/src/app/Neuron/Web/View.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/test/Neuron/VersionSpec.hs, neuron/test/Neuron/Zettelkasten/ZettelSpec.hs
=> Normalize JSON output

neuron/src/app/Neuron/Web/View.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/Theme.hs, neuron/src/lib/Neuron/Web/Zettel/CSS.hs
Adjust the layout and css to make switching theme colors straightforward.
=> Switchable theme colors

neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Theme.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs
=> Allow showing ID next to link title

neuron/src/app/Neuron/CLI/New.hs
=> Fix date in template org zettel

.github/workflows/ci.yaml
Fixes https://github.com/srid/neuron-template/issues/2
=> Create nix-bundle for master branch only

.github/workflows/ci.yaml, .github/workflows/publish.yaml, .gitignore
=> Setup automated nightly releases (tested)

.github/workflows/ci.yaml, docker.nix, neuron/neuron.cabal
=> Nightly docker images

CHANGELOG.md, neuron/neuron.cabal, neuron/test/Neuron/VersionSpec.hs
=> Release 0.6.0.0

neuron/src/lib/Neuron/Web/Query/View.hs
=> Change zettel ::after into a superscript

neuron/src/lib/Neuron/Web/Query/View.hs
=> Revert "Change zettel ::after into a superscript"

neuron/neuron.cabal, project.nix
https://github.com/haskell/haskell-language-server/blob/master/ChangeLog.md#030
Looking at the ChangeLog, 0.4 is already released. Wonder how long before nixpkgs gets it ...
=> Advance nixpkgs, for HLS 0.3

guide/2013101.md
=> add my website: fiatjaf.alhur.es

neuron/neuron.cabal
Makes available foldSome which is used in neuron/src/app/Neuron/CLI/Open.hs
=> Add lower bound dependent-sum >= 0.7

.github/workflows/ci.yaml, .github/workflows/publish.yaml, ci.nix, nixpkgs.nix, project.nix
macOS Nix install in particular went from 3 minutes to 20 seconds.
cf. https://twitter.com/domenkozar/status/1308064089554419713
=> CI: speed up Nix install

CHANGELOG.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/Search.hs
- To address #428 
- Also resolves #392
=> Embed neuron-search script

CHANGELOG.md, neuron/neuron.cabal, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Web/Generate.hs, neuron/src/lib/Neuron/Web/Query/View.hs, neuron/src/lib/Neuron/Web/Widget.hs, neuron/src/lib/Neuron/Web/ZIndex.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Build.hs, neuron/src/lib/Neuron/Zettelkasten/ID.hs, neuron/src/lib/Neuron/Zettelkasten/Query.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Error.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel/Parser.hs, neuron/test/Neuron/Zettelkasten/Query/ParserSpec.hs, neuron/test/Neuron/Zettelkasten/ZettelSpec.hs
=> Simplify 'zettel not found' error message in HTML

CHANGELOG.md, neuron/neuron.cabal, neuron/src/lib/Data/Graph/Labelled/Algorithm.hs, neuron/src/lib/Neuron/Reader/Markdown.hs, neuron/src/lib/Neuron/Web/Zettel/CSS.hs, neuron/src/lib/Neuron/Web/Zettel/View.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Build.hs, neuron/src/lib/Neuron/Zettelkasten/Graph/Type.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Eval.hs, neuron/src/lib/Neuron/Zettelkasten/Query/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel/Parser.hs, neuron/src/lib/Text/Pandoc/Util.hs, neuron/test/Neuron/Config/AliasSpec.hs
=> Backlinks surrounding context

neuron/src/lib/Neuron/Reader/Markdown.hs
=> Fix parsing of lists containing pipe characters

.github/workflows/ci.yaml, .github/workflows/publish.yaml, CHANGELOG.md, neuron/neuron.cabal, neuron/src/lib/Neuron/Reader/Markdown.hs
=> Revert #467

CHANGELOG.md, doc/Guide/Creating and Editing zettels.md, doc/Guide/Creating and Editing zettels/editor.md, doc/Guide/Plugins/Directory Tree.md, doc/Guide/Plugins/Linking.md, doc/Guide/Plugins/Linking/Folgezettel Links.md, doc/Guide/Plugins/Tags/Tag Queries.md, doc/Guide/Plugins/Uplink Tree.md, doc/Guide/Web interface.md, doc/Guide/Web interface/Customizing the generated website.md, doc/Guide/Web interface/Customizing the generated website/Custom JavaScript and CSS.md, doc/Guide/Web interface/Graph visualization.md, doc/Guide/Web interface/Graph visualization/folgezettel-heterarchy.md, doc/Guide/Web interface/Graph visualization/impulse-feature.md, doc/Guide/Zettel Markdown.md, doc/Guide/Zettel Markdown/2016401.md, doc/Guide/Zettel Markdown/metadata.md, doc/Installing.md, doc/Installing/Declarative Install.md, doc/Zettelkasten.md, doc/Zettelkasten/Heterarchy.md, doc/index.md, neuron/neuron.cabal, neuron/src/lib/Data/Graph/Labelled.hs, neuron/src/lib/Data/Graph/Labelled/Algorithm.hs, neuron/src/lib/Neuron/Plugin/Plugins/Links.hs, neuron/src/lib/Neuron/Plugin/Plugins/UpTree.hs, neuron/src/lib/Neuron/Zettelkasten/Connection.hs, neuron/src/lib/Neuron/Zettelkasten/Graph.hs, neuron/src/lib/Neuron/Zettelkasten/Zettel/Parser.hs
=> Add #[[foo]] and [[foo]]# style links

CHANGELOG.md, doc/Guide/Web interface.md, neuron/neuron.cabal, neuron/src/app/Neuron/Backend.hs, neuron/src/app/Neuron/CLI/App.hs, neuron/src/app/Neuron/CLI/Parser.hs, neuron/src/app/Neuron/CLI/Types.hs, neuron/src/app/Neuron/Frontend/Static/Html.hs, neuron/src/app/Neuron/Frontend/Static/StructuredData.hs, neuron/src/app/Neuron/Reactor.hs, neuron/src/app/Neuron/Reactor/Build.hs, neuron/src/lib/Neuron/Frontend/Route.hs
=> Add `neuron gen --pretty-urls` to use pretty URLs

neuron/src/app/Neuron/CLI/App.hs, neuron/src/app/Neuron/CLI/Logging.hs
=> Use colors in logs only if terminal supports it.

README.md, doc/index.md
For a donation system outside of GitHub.
=> Add liberapay links

doc/Examples.md
Really enjoying this tool so far and learning more about the zettelkasten method. I'd like to share my site as an example.
=> Add devonmorris.dev

CHANGELOG.md, neuron.cabal, src/Neuron/Zettelkasten/ID.hs
=> feat: Added § in whitelist

neuron.cabal
This enable compilation on a recent nixpkgs.
=> Widen commonmark bound
